// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_battle.proto

#include "client_battle.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR cli_3d_skill_req::cli_3d_skill_req(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.skill_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct cli_3d_skill_reqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR cli_3d_skill_reqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~cli_3d_skill_reqDefaultTypeInternal() {}
  union {
    cli_3d_skill_req _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 cli_3d_skill_reqDefaultTypeInternal _cli_3d_skill_req_default_instance_;
PROTOBUF_CONSTEXPR cli_3d_skill_res::cli_3d_skill_res(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.entity_id_)*/uint64_t{0u}
  , /*decltype(_impl_.skill_cfg_id_)*/0u
  , /*decltype(_impl_.combo_index_)*/0u
  , /*decltype(_impl_.err_code_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct cli_3d_skill_resDefaultTypeInternal {
  PROTOBUF_CONSTEXPR cli_3d_skill_resDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~cli_3d_skill_resDefaultTypeInternal() {}
  union {
    cli_3d_skill_res _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 cli_3d_skill_resDefaultTypeInternal _cli_3d_skill_res_default_instance_;
PROTOBUF_CONSTEXPR cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse::cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUseDefaultTypeInternal() {}
  union {
    cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUseDefaultTypeInternal _cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR cli_3d_hit_ntf::cli_3d_hit_ntf(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.target_attr_changes_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_.attacker_entity_id_)*/uint64_t{0u}
  , /*decltype(_impl_.target_entity_id_)*/uint64_t{0u}
  , /*decltype(_impl_.skill_cfg_id_)*/0u
  , /*decltype(_impl_.combo_index_)*/0u
  , /*decltype(_impl_.damage_)*/0
  , /*decltype(_impl_.hit_state_flag_)*/0u
  , /*decltype(_impl_.is_critical_)*/false
  , /*decltype(_impl_.target_dead_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct cli_3d_hit_ntfDefaultTypeInternal {
  PROTOBUF_CONSTEXPR cli_3d_hit_ntfDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~cli_3d_hit_ntfDefaultTypeInternal() {}
  union {
    cli_3d_hit_ntf _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 cli_3d_hit_ntfDefaultTypeInternal _cli_3d_hit_ntf_default_instance_;
static ::_pb::Metadata file_level_metadata_client_5fbattle_2eproto[4];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_client_5fbattle_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_client_5fbattle_2eproto = nullptr;

const uint32_t TableStruct_client_5fbattle_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::cli_3d_skill_req, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::cli_3d_skill_req, _impl_.skill_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::cli_3d_skill_res, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::cli_3d_skill_res, _impl_.entity_id_),
  PROTOBUF_FIELD_OFFSET(::cli_3d_skill_res, _impl_.skill_cfg_id_),
  PROTOBUF_FIELD_OFFSET(::cli_3d_skill_res, _impl_.combo_index_),
  PROTOBUF_FIELD_OFFSET(::cli_3d_skill_res, _impl_.err_code_),
  PROTOBUF_FIELD_OFFSET(::cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::cli_3d_hit_ntf, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::cli_3d_hit_ntf, _impl_.attacker_entity_id_),
  PROTOBUF_FIELD_OFFSET(::cli_3d_hit_ntf, _impl_.target_entity_id_),
  PROTOBUF_FIELD_OFFSET(::cli_3d_hit_ntf, _impl_.skill_cfg_id_),
  PROTOBUF_FIELD_OFFSET(::cli_3d_hit_ntf, _impl_.combo_index_),
  PROTOBUF_FIELD_OFFSET(::cli_3d_hit_ntf, _impl_.damage_),
  PROTOBUF_FIELD_OFFSET(::cli_3d_hit_ntf, _impl_.hit_state_flag_),
  PROTOBUF_FIELD_OFFSET(::cli_3d_hit_ntf, _impl_.is_critical_),
  PROTOBUF_FIELD_OFFSET(::cli_3d_hit_ntf, _impl_.target_dead_),
  PROTOBUF_FIELD_OFFSET(::cli_3d_hit_ntf, _impl_.target_attr_changes_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::cli_3d_skill_req)},
  { 7, -1, -1, sizeof(::cli_3d_skill_res)},
  { 17, 25, -1, sizeof(::cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse)},
  { 27, -1, -1, sizeof(::cli_3d_hit_ntf)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_cli_3d_skill_req_default_instance_._instance,
  &::_cli_3d_skill_res_default_instance_._instance,
  &::_cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse_default_instance_._instance,
  &::_cli_3d_hit_ntf_default_instance_._instance,
};

const char descriptor_table_protodef_client_5fbattle_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023client_battle.proto\032\023client_common.pro"
  "to\"5\n\020cli_3d_skill_req\022!\n\005skill\030\001 \001(\0132\022."
  "entity_skill_data\"o\n\020cli_3d_skill_res\022\021\n"
  "\tentity_id\030\001 \001(\004\022\024\n\014skill_cfg_id\030\002 \001(\r\022\023"
  "\n\013combo_index\030\003 \001(\r\022\035\n\010err_code\030\004 \001(\0162\013."
  "error_code\"\302\002\n\016cli_3d_hit_ntf\022\032\n\022attacke"
  "r_entity_id\030\001 \001(\004\022\030\n\020target_entity_id\030\002 "
  "\001(\004\022\024\n\014skill_cfg_id\030\003 \001(\r\022\023\n\013combo_index"
  "\030\004 \001(\r\022\016\n\006damage\030\005 \001(\005\022\026\n\016hit_state_flag"
  "\030\006 \001(\r\022\023\n\013is_critical\030\007 \001(\010\022\023\n\013target_de"
  "ad\030\010 \001(\010\022C\n\023target_attr_changes\030\t \003(\0132&."
  "cli_3d_hit_ntf.TargetAttrChangesEntry\0328\n"
  "\026TargetAttrChangesEntry\022\013\n\003key\030\001 \001(\005\022\r\n\005"
  "value\030\002 \001(\003:\0028\001b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_client_5fbattle_2eproto_deps[1] = {
  &::descriptor_table_client_5fcommon_2eproto,
};
static ::_pbi::once_flag descriptor_table_client_5fbattle_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_client_5fbattle_2eproto = {
    false, false, 543, descriptor_table_protodef_client_5fbattle_2eproto,
    "client_battle.proto",
    &descriptor_table_client_5fbattle_2eproto_once, descriptor_table_client_5fbattle_2eproto_deps, 1, 4,
    schemas, file_default_instances, TableStruct_client_5fbattle_2eproto::offsets,
    file_level_metadata_client_5fbattle_2eproto, file_level_enum_descriptors_client_5fbattle_2eproto,
    file_level_service_descriptors_client_5fbattle_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_client_5fbattle_2eproto_getter() {
  return &descriptor_table_client_5fbattle_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_client_5fbattle_2eproto(&descriptor_table_client_5fbattle_2eproto);

// ===================================================================

class cli_3d_skill_req::_Internal {
 public:
  static const ::entity_skill_data& skill(const cli_3d_skill_req* msg);
};

const ::entity_skill_data&
cli_3d_skill_req::_Internal::skill(const cli_3d_skill_req* msg) {
  return *msg->_impl_.skill_;
}
void cli_3d_skill_req::clear_skill() {
  if (GetArenaForAllocation() == nullptr && _impl_.skill_ != nullptr) {
    delete _impl_.skill_;
  }
  _impl_.skill_ = nullptr;
}
cli_3d_skill_req::cli_3d_skill_req(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:cli_3d_skill_req)
}
cli_3d_skill_req::cli_3d_skill_req(const cli_3d_skill_req& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  cli_3d_skill_req* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.skill_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_skill()) {
    _this->_impl_.skill_ = new ::entity_skill_data(*from._impl_.skill_);
  }
  // @@protoc_insertion_point(copy_constructor:cli_3d_skill_req)
}

inline void cli_3d_skill_req::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.skill_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

cli_3d_skill_req::~cli_3d_skill_req() {
  // @@protoc_insertion_point(destructor:cli_3d_skill_req)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void cli_3d_skill_req::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.skill_;
}

void cli_3d_skill_req::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void cli_3d_skill_req::Clear() {
// @@protoc_insertion_point(message_clear_start:cli_3d_skill_req)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.skill_ != nullptr) {
    delete _impl_.skill_;
  }
  _impl_.skill_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* cli_3d_skill_req::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .entity_skill_data skill = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_skill(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* cli_3d_skill_req::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cli_3d_skill_req)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .entity_skill_data skill = 1;
  if (this->_internal_has_skill()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::skill(this),
        _Internal::skill(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cli_3d_skill_req)
  return target;
}

size_t cli_3d_skill_req::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cli_3d_skill_req)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .entity_skill_data skill = 1;
  if (this->_internal_has_skill()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.skill_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData cli_3d_skill_req::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    cli_3d_skill_req::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*cli_3d_skill_req::GetClassData() const { return &_class_data_; }


void cli_3d_skill_req::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<cli_3d_skill_req*>(&to_msg);
  auto& from = static_cast<const cli_3d_skill_req&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:cli_3d_skill_req)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_skill()) {
    _this->_internal_mutable_skill()->::entity_skill_data::MergeFrom(
        from._internal_skill());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void cli_3d_skill_req::CopyFrom(const cli_3d_skill_req& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cli_3d_skill_req)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool cli_3d_skill_req::IsInitialized() const {
  return true;
}

void cli_3d_skill_req::InternalSwap(cli_3d_skill_req* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.skill_, other->_impl_.skill_);
}

::PROTOBUF_NAMESPACE_ID::Metadata cli_3d_skill_req::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_client_5fbattle_2eproto_getter, &descriptor_table_client_5fbattle_2eproto_once,
      file_level_metadata_client_5fbattle_2eproto[0]);
}

// ===================================================================

class cli_3d_skill_res::_Internal {
 public:
};

cli_3d_skill_res::cli_3d_skill_res(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:cli_3d_skill_res)
}
cli_3d_skill_res::cli_3d_skill_res(const cli_3d_skill_res& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  cli_3d_skill_res* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.entity_id_){}
    , decltype(_impl_.skill_cfg_id_){}
    , decltype(_impl_.combo_index_){}
    , decltype(_impl_.err_code_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.entity_id_, &from._impl_.entity_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.err_code_) -
    reinterpret_cast<char*>(&_impl_.entity_id_)) + sizeof(_impl_.err_code_));
  // @@protoc_insertion_point(copy_constructor:cli_3d_skill_res)
}

inline void cli_3d_skill_res::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.entity_id_){uint64_t{0u}}
    , decltype(_impl_.skill_cfg_id_){0u}
    , decltype(_impl_.combo_index_){0u}
    , decltype(_impl_.err_code_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

cli_3d_skill_res::~cli_3d_skill_res() {
  // @@protoc_insertion_point(destructor:cli_3d_skill_res)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void cli_3d_skill_res::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void cli_3d_skill_res::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void cli_3d_skill_res::Clear() {
// @@protoc_insertion_point(message_clear_start:cli_3d_skill_res)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.entity_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.err_code_) -
      reinterpret_cast<char*>(&_impl_.entity_id_)) + sizeof(_impl_.err_code_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* cli_3d_skill_res::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 entity_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.entity_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 skill_cfg_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.skill_cfg_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 combo_index = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.combo_index_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .error_code err_code = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_err_code(static_cast<::error_code>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* cli_3d_skill_res::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cli_3d_skill_res)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 entity_id = 1;
  if (this->_internal_entity_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_entity_id(), target);
  }

  // uint32 skill_cfg_id = 2;
  if (this->_internal_skill_cfg_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_skill_cfg_id(), target);
  }

  // uint32 combo_index = 3;
  if (this->_internal_combo_index() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_combo_index(), target);
  }

  // .error_code err_code = 4;
  if (this->_internal_err_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      4, this->_internal_err_code(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cli_3d_skill_res)
  return target;
}

size_t cli_3d_skill_res::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cli_3d_skill_res)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 entity_id = 1;
  if (this->_internal_entity_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_entity_id());
  }

  // uint32 skill_cfg_id = 2;
  if (this->_internal_skill_cfg_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_skill_cfg_id());
  }

  // uint32 combo_index = 3;
  if (this->_internal_combo_index() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_combo_index());
  }

  // .error_code err_code = 4;
  if (this->_internal_err_code() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_err_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData cli_3d_skill_res::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    cli_3d_skill_res::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*cli_3d_skill_res::GetClassData() const { return &_class_data_; }


void cli_3d_skill_res::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<cli_3d_skill_res*>(&to_msg);
  auto& from = static_cast<const cli_3d_skill_res&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:cli_3d_skill_res)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_entity_id() != 0) {
    _this->_internal_set_entity_id(from._internal_entity_id());
  }
  if (from._internal_skill_cfg_id() != 0) {
    _this->_internal_set_skill_cfg_id(from._internal_skill_cfg_id());
  }
  if (from._internal_combo_index() != 0) {
    _this->_internal_set_combo_index(from._internal_combo_index());
  }
  if (from._internal_err_code() != 0) {
    _this->_internal_set_err_code(from._internal_err_code());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void cli_3d_skill_res::CopyFrom(const cli_3d_skill_res& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cli_3d_skill_res)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool cli_3d_skill_res::IsInitialized() const {
  return true;
}

void cli_3d_skill_res::InternalSwap(cli_3d_skill_res* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(cli_3d_skill_res, _impl_.err_code_)
      + sizeof(cli_3d_skill_res::_impl_.err_code_)
      - PROTOBUF_FIELD_OFFSET(cli_3d_skill_res, _impl_.entity_id_)>(
          reinterpret_cast<char*>(&_impl_.entity_id_),
          reinterpret_cast<char*>(&other->_impl_.entity_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata cli_3d_skill_res::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_client_5fbattle_2eproto_getter, &descriptor_table_client_5fbattle_2eproto_once,
      file_level_metadata_client_5fbattle_2eproto[1]);
}

// ===================================================================

cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse::cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse() {}
cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse::cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse::MergeFrom(const cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_client_5fbattle_2eproto_getter, &descriptor_table_client_5fbattle_2eproto_once,
      file_level_metadata_client_5fbattle_2eproto[2]);
}

// ===================================================================

class cli_3d_hit_ntf::_Internal {
 public:
};

cli_3d_hit_ntf::cli_3d_hit_ntf(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  if (arena != nullptr && !is_message_owned) {
    arena->OwnCustomDestructor(this, &cli_3d_hit_ntf::ArenaDtor);
  }
  // @@protoc_insertion_point(arena_constructor:cli_3d_hit_ntf)
}
cli_3d_hit_ntf::cli_3d_hit_ntf(const cli_3d_hit_ntf& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  cli_3d_hit_ntf* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      /*decltype(_impl_.target_attr_changes_)*/{}
    , decltype(_impl_.attacker_entity_id_){}
    , decltype(_impl_.target_entity_id_){}
    , decltype(_impl_.skill_cfg_id_){}
    , decltype(_impl_.combo_index_){}
    , decltype(_impl_.damage_){}
    , decltype(_impl_.hit_state_flag_){}
    , decltype(_impl_.is_critical_){}
    , decltype(_impl_.target_dead_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.target_attr_changes_.MergeFrom(from._impl_.target_attr_changes_);
  ::memcpy(&_impl_.attacker_entity_id_, &from._impl_.attacker_entity_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.target_dead_) -
    reinterpret_cast<char*>(&_impl_.attacker_entity_id_)) + sizeof(_impl_.target_dead_));
  // @@protoc_insertion_point(copy_constructor:cli_3d_hit_ntf)
}

inline void cli_3d_hit_ntf::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      /*decltype(_impl_.target_attr_changes_)*/{::_pbi::ArenaInitialized(), arena}
    , decltype(_impl_.attacker_entity_id_){uint64_t{0u}}
    , decltype(_impl_.target_entity_id_){uint64_t{0u}}
    , decltype(_impl_.skill_cfg_id_){0u}
    , decltype(_impl_.combo_index_){0u}
    , decltype(_impl_.damage_){0}
    , decltype(_impl_.hit_state_flag_){0u}
    , decltype(_impl_.is_critical_){false}
    , decltype(_impl_.target_dead_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

cli_3d_hit_ntf::~cli_3d_hit_ntf() {
  // @@protoc_insertion_point(destructor:cli_3d_hit_ntf)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    ArenaDtor(this);
    return;
  }
  SharedDtor();
}

inline void cli_3d_hit_ntf::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.target_attr_changes_.Destruct();
  _impl_.target_attr_changes_.~MapField();
}

void cli_3d_hit_ntf::ArenaDtor(void* object) {
  cli_3d_hit_ntf* _this = reinterpret_cast< cli_3d_hit_ntf* >(object);
  _this->_impl_.target_attr_changes_.Destruct();
}
void cli_3d_hit_ntf::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void cli_3d_hit_ntf::Clear() {
// @@protoc_insertion_point(message_clear_start:cli_3d_hit_ntf)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.target_attr_changes_.Clear();
  ::memset(&_impl_.attacker_entity_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.target_dead_) -
      reinterpret_cast<char*>(&_impl_.attacker_entity_id_)) + sizeof(_impl_.target_dead_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* cli_3d_hit_ntf::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 attacker_entity_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.attacker_entity_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 target_entity_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.target_entity_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 skill_cfg_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.skill_cfg_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 combo_index = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.combo_index_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 damage = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.damage_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 hit_state_flag = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.hit_state_flag_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool is_critical = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.is_critical_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool target_dead = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _impl_.target_dead_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // map<int32, int64> target_attr_changes = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 74)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.target_attr_changes_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<74>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* cli_3d_hit_ntf::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cli_3d_hit_ntf)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 attacker_entity_id = 1;
  if (this->_internal_attacker_entity_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_attacker_entity_id(), target);
  }

  // uint64 target_entity_id = 2;
  if (this->_internal_target_entity_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_target_entity_id(), target);
  }

  // uint32 skill_cfg_id = 3;
  if (this->_internal_skill_cfg_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_skill_cfg_id(), target);
  }

  // uint32 combo_index = 4;
  if (this->_internal_combo_index() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(4, this->_internal_combo_index(), target);
  }

  // int32 damage = 5;
  if (this->_internal_damage() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_damage(), target);
  }

  // uint32 hit_state_flag = 6;
  if (this->_internal_hit_state_flag() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(6, this->_internal_hit_state_flag(), target);
  }

  // bool is_critical = 7;
  if (this->_internal_is_critical() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(7, this->_internal_is_critical(), target);
  }

  // bool target_dead = 8;
  if (this->_internal_target_dead() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(8, this->_internal_target_dead(), target);
  }

  // map<int32, int64> target_attr_changes = 9;
  if (!this->_internal_target_attr_changes().empty()) {
    using MapType = ::_pb::Map<int32_t, int64_t>;
    using WireHelper = cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_target_attr_changes();

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterFlat<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(9, entry.first, entry.second, target, stream);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(9, entry.first, entry.second, target, stream);
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cli_3d_hit_ntf)
  return target;
}

size_t cli_3d_hit_ntf::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cli_3d_hit_ntf)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<int32, int64> target_attr_changes = 9;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_target_attr_changes_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< int32_t, int64_t >::const_iterator
      it = this->_internal_target_attr_changes().begin();
      it != this->_internal_target_attr_changes().end(); ++it) {
    total_size += cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // uint64 attacker_entity_id = 1;
  if (this->_internal_attacker_entity_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_attacker_entity_id());
  }

  // uint64 target_entity_id = 2;
  if (this->_internal_target_entity_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_target_entity_id());
  }

  // uint32 skill_cfg_id = 3;
  if (this->_internal_skill_cfg_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_skill_cfg_id());
  }

  // uint32 combo_index = 4;
  if (this->_internal_combo_index() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_combo_index());
  }

  // int32 damage = 5;
  if (this->_internal_damage() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_damage());
  }

  // uint32 hit_state_flag = 6;
  if (this->_internal_hit_state_flag() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_hit_state_flag());
  }

  // bool is_critical = 7;
  if (this->_internal_is_critical() != 0) {
    total_size += 1 + 1;
  }

  // bool target_dead = 8;
  if (this->_internal_target_dead() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData cli_3d_hit_ntf::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    cli_3d_hit_ntf::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*cli_3d_hit_ntf::GetClassData() const { return &_class_data_; }


void cli_3d_hit_ntf::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<cli_3d_hit_ntf*>(&to_msg);
  auto& from = static_cast<const cli_3d_hit_ntf&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:cli_3d_hit_ntf)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.target_attr_changes_.MergeFrom(from._impl_.target_attr_changes_);
  if (from._internal_attacker_entity_id() != 0) {
    _this->_internal_set_attacker_entity_id(from._internal_attacker_entity_id());
  }
  if (from._internal_target_entity_id() != 0) {
    _this->_internal_set_target_entity_id(from._internal_target_entity_id());
  }
  if (from._internal_skill_cfg_id() != 0) {
    _this->_internal_set_skill_cfg_id(from._internal_skill_cfg_id());
  }
  if (from._internal_combo_index() != 0) {
    _this->_internal_set_combo_index(from._internal_combo_index());
  }
  if (from._internal_damage() != 0) {
    _this->_internal_set_damage(from._internal_damage());
  }
  if (from._internal_hit_state_flag() != 0) {
    _this->_internal_set_hit_state_flag(from._internal_hit_state_flag());
  }
  if (from._internal_is_critical() != 0) {
    _this->_internal_set_is_critical(from._internal_is_critical());
  }
  if (from._internal_target_dead() != 0) {
    _this->_internal_set_target_dead(from._internal_target_dead());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void cli_3d_hit_ntf::CopyFrom(const cli_3d_hit_ntf& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cli_3d_hit_ntf)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool cli_3d_hit_ntf::IsInitialized() const {
  return true;
}

void cli_3d_hit_ntf::InternalSwap(cli_3d_hit_ntf* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.target_attr_changes_.InternalSwap(&other->_impl_.target_attr_changes_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(cli_3d_hit_ntf, _impl_.target_dead_)
      + sizeof(cli_3d_hit_ntf::_impl_.target_dead_)
      - PROTOBUF_FIELD_OFFSET(cli_3d_hit_ntf, _impl_.attacker_entity_id_)>(
          reinterpret_cast<char*>(&_impl_.attacker_entity_id_),
          reinterpret_cast<char*>(&other->_impl_.attacker_entity_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata cli_3d_hit_ntf::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_client_5fbattle_2eproto_getter, &descriptor_table_client_5fbattle_2eproto_once,
      file_level_metadata_client_5fbattle_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::cli_3d_skill_req*
Arena::CreateMaybeMessage< ::cli_3d_skill_req >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cli_3d_skill_req >(arena);
}
template<> PROTOBUF_NOINLINE ::cli_3d_skill_res*
Arena::CreateMaybeMessage< ::cli_3d_skill_res >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cli_3d_skill_res >(arena);
}
template<> PROTOBUF_NOINLINE ::cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse*
Arena::CreateMaybeMessage< ::cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::cli_3d_hit_ntf*
Arena::CreateMaybeMessage< ::cli_3d_hit_ntf >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cli_3d_hit_ntf >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
