// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_battle.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_client_5fbattle_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_client_5fbattle_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/util/json_util.h>
#include <regex>
#include "client_common.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_client_5fbattle_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_client_5fbattle_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_client_5fbattle_2eproto;
class cli_3d_hit_ntf;
struct cli_3d_hit_ntfDefaultTypeInternal;
extern cli_3d_hit_ntfDefaultTypeInternal _cli_3d_hit_ntf_default_instance_;
class cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse;
struct cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUseDefaultTypeInternal;
extern cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUseDefaultTypeInternal _cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse_default_instance_;
class cli_3d_skill_req;
struct cli_3d_skill_reqDefaultTypeInternal;
extern cli_3d_skill_reqDefaultTypeInternal _cli_3d_skill_req_default_instance_;
class cli_3d_skill_res;
struct cli_3d_skill_resDefaultTypeInternal;
extern cli_3d_skill_resDefaultTypeInternal _cli_3d_skill_res_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::cli_3d_hit_ntf* Arena::CreateMaybeMessage<::cli_3d_hit_ntf>(Arena*);
template<> ::cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse* Arena::CreateMaybeMessage<::cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse>(Arena*);
template<> ::cli_3d_skill_req* Arena::CreateMaybeMessage<::cli_3d_skill_req>(Arena*);
template<> ::cli_3d_skill_res* Arena::CreateMaybeMessage<::cli_3d_skill_res>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class cli_3d_skill_req final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cli_3d_skill_req) */ {

 public:
  const std::string msg_name() override
  {
    return "cli_3d_skill_req";    
  }
  uint32_t msg_id() override
  {
    return 3201020581;
  }
  static uint32_t get_msg_id()
  {
    return 3201020581;
  }
  
  const std::string to_json() override
  {
    std::string proto_json;
    google::protobuf::util::MessageToJsonString(*this, &proto_json);
    
    std::string name_and_id = R"({"msg_name":"cli_3d_skill_req","msg_id":3201020581)";
    if (proto_json.size() > 2)
    {
      name_and_id += ",";
    }
    proto_json.replace(0, 1, name_and_id);
    
    return proto_json;
  }
  
   void from_json(const std::string& proto_json) override
   {
     std::regex pattern(R"(^\{"msg_name":"[^"]+","msg_id":[0-9]+,)");
     std::smatch match;
     std::string msg_content = proto_json;
     if (std::regex_search(proto_json, match, pattern))
     {
         msg_content.replace(0, match[0].length(), "{");
     }

     google::protobuf::util::JsonStringToMessage(msg_content, this);
   }
  
 public:
  inline cli_3d_skill_req() : cli_3d_skill_req(nullptr) {}
  ~cli_3d_skill_req() override;
  explicit PROTOBUF_CONSTEXPR cli_3d_skill_req(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  cli_3d_skill_req(const cli_3d_skill_req& from);
  cli_3d_skill_req(cli_3d_skill_req&& from) noexcept
    : cli_3d_skill_req() {
    *this = ::std::move(from);
  }

  inline cli_3d_skill_req& operator=(const cli_3d_skill_req& from) {
    CopyFrom(from);
    return *this;
  }
  inline cli_3d_skill_req& operator=(cli_3d_skill_req&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const cli_3d_skill_req& default_instance() {
    return *internal_default_instance();
  }
  static inline const cli_3d_skill_req* internal_default_instance() {
    return reinterpret_cast<const cli_3d_skill_req*>(
               &_cli_3d_skill_req_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(cli_3d_skill_req& a, cli_3d_skill_req& b) {
    a.Swap(&b);
  }
  inline void Swap(cli_3d_skill_req* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(cli_3d_skill_req* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  cli_3d_skill_req* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<cli_3d_skill_req>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const cli_3d_skill_req& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const cli_3d_skill_req& from) {
    cli_3d_skill_req::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(cli_3d_skill_req* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cli_3d_skill_req";
  }
  protected:
  explicit cli_3d_skill_req(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSkillFieldNumber = 1,
  };
  // .entity_skill_data skill = 1;
  bool has_skill() const;
  private:
  bool _internal_has_skill() const;
  public:
  void clear_skill();
  const ::entity_skill_data& skill() const;
  PROTOBUF_NODISCARD ::entity_skill_data* release_skill();
  ::entity_skill_data* mutable_skill();
  void set_allocated_skill(::entity_skill_data* skill);
  private:
  const ::entity_skill_data& _internal_skill() const;
  ::entity_skill_data* _internal_mutable_skill();
  public:
  void unsafe_arena_set_allocated_skill(
      ::entity_skill_data* skill);
  ::entity_skill_data* unsafe_arena_release_skill();

  // @@protoc_insertion_point(class_scope:cli_3d_skill_req)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::entity_skill_data* skill_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_client_5fbattle_2eproto;
};
// -------------------------------------------------------------------

class cli_3d_skill_res final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cli_3d_skill_res) */ {

 public:
  const std::string msg_name() override
  {
    return "cli_3d_skill_res";    
  }
  uint32_t msg_id() override
  {
    return 1355142025;
  }
  static uint32_t get_msg_id()
  {
    return 1355142025;
  }
  
  const std::string to_json() override
  {
    std::string proto_json;
    google::protobuf::util::MessageToJsonString(*this, &proto_json);
    
    std::string name_and_id = R"({"msg_name":"cli_3d_skill_res","msg_id":1355142025)";
    if (proto_json.size() > 2)
    {
      name_and_id += ",";
    }
    proto_json.replace(0, 1, name_and_id);
    
    return proto_json;
  }
  
   void from_json(const std::string& proto_json) override
   {
     std::regex pattern(R"(^\{"msg_name":"[^"]+","msg_id":[0-9]+,)");
     std::smatch match;
     std::string msg_content = proto_json;
     if (std::regex_search(proto_json, match, pattern))
     {
         msg_content.replace(0, match[0].length(), "{");
     }

     google::protobuf::util::JsonStringToMessage(msg_content, this);
   }
  
 public:
  inline cli_3d_skill_res() : cli_3d_skill_res(nullptr) {}
  ~cli_3d_skill_res() override;
  explicit PROTOBUF_CONSTEXPR cli_3d_skill_res(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  cli_3d_skill_res(const cli_3d_skill_res& from);
  cli_3d_skill_res(cli_3d_skill_res&& from) noexcept
    : cli_3d_skill_res() {
    *this = ::std::move(from);
  }

  inline cli_3d_skill_res& operator=(const cli_3d_skill_res& from) {
    CopyFrom(from);
    return *this;
  }
  inline cli_3d_skill_res& operator=(cli_3d_skill_res&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const cli_3d_skill_res& default_instance() {
    return *internal_default_instance();
  }
  static inline const cli_3d_skill_res* internal_default_instance() {
    return reinterpret_cast<const cli_3d_skill_res*>(
               &_cli_3d_skill_res_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(cli_3d_skill_res& a, cli_3d_skill_res& b) {
    a.Swap(&b);
  }
  inline void Swap(cli_3d_skill_res* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(cli_3d_skill_res* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  cli_3d_skill_res* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<cli_3d_skill_res>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const cli_3d_skill_res& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const cli_3d_skill_res& from) {
    cli_3d_skill_res::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(cli_3d_skill_res* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cli_3d_skill_res";
  }
  protected:
  explicit cli_3d_skill_res(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEntityIdFieldNumber = 1,
    kSkillCfgIdFieldNumber = 2,
    kComboIndexFieldNumber = 3,
    kErrCodeFieldNumber = 4,
  };
  // uint64 entity_id = 1;
  void clear_entity_id();
  uint64_t entity_id() const;
  void set_entity_id(uint64_t value);
  private:
  uint64_t _internal_entity_id() const;
  void _internal_set_entity_id(uint64_t value);
  public:

  // uint32 skill_cfg_id = 2;
  void clear_skill_cfg_id();
  uint32_t skill_cfg_id() const;
  void set_skill_cfg_id(uint32_t value);
  private:
  uint32_t _internal_skill_cfg_id() const;
  void _internal_set_skill_cfg_id(uint32_t value);
  public:

  // uint32 combo_index = 3;
  void clear_combo_index();
  uint32_t combo_index() const;
  void set_combo_index(uint32_t value);
  private:
  uint32_t _internal_combo_index() const;
  void _internal_set_combo_index(uint32_t value);
  public:

  // .error_code err_code = 4;
  void clear_err_code();
  ::error_code err_code() const;
  void set_err_code(::error_code value);
  private:
  ::error_code _internal_err_code() const;
  void _internal_set_err_code(::error_code value);
  public:

  // @@protoc_insertion_point(class_scope:cli_3d_skill_res)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t entity_id_;
    uint32_t skill_cfg_id_;
    uint32_t combo_index_;
    int err_code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_client_5fbattle_2eproto;
};
// -------------------------------------------------------------------

class cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse, 
    int32_t, int64_t,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT64> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse, 
    int32_t, int64_t,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT64> SuperType;
  cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse& other);
  static const cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse*>(&_cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_client_5fbattle_2eproto;
};

// -------------------------------------------------------------------

class cli_3d_hit_ntf final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cli_3d_hit_ntf) */ {

 public:
  const std::string msg_name() override
  {
    return "cli_3d_hit_ntf";    
  }
  uint32_t msg_id() override
  {
    return 1089166412;
  }
  static uint32_t get_msg_id()
  {
    return 1089166412;
  }
  
  const std::string to_json() override
  {
    std::string proto_json;
    google::protobuf::util::MessageToJsonString(*this, &proto_json);
    
    std::string name_and_id = R"({"msg_name":"cli_3d_hit_ntf","msg_id":1089166412)";
    if (proto_json.size() > 2)
    {
      name_and_id += ",";
    }
    proto_json.replace(0, 1, name_and_id);
    
    return proto_json;
  }
  
   void from_json(const std::string& proto_json) override
   {
     std::regex pattern(R"(^\{"msg_name":"[^"]+","msg_id":[0-9]+,)");
     std::smatch match;
     std::string msg_content = proto_json;
     if (std::regex_search(proto_json, match, pattern))
     {
         msg_content.replace(0, match[0].length(), "{");
     }

     google::protobuf::util::JsonStringToMessage(msg_content, this);
   }
  
 public:
  inline cli_3d_hit_ntf() : cli_3d_hit_ntf(nullptr) {}
  ~cli_3d_hit_ntf() override;
  explicit PROTOBUF_CONSTEXPR cli_3d_hit_ntf(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  cli_3d_hit_ntf(const cli_3d_hit_ntf& from);
  cli_3d_hit_ntf(cli_3d_hit_ntf&& from) noexcept
    : cli_3d_hit_ntf() {
    *this = ::std::move(from);
  }

  inline cli_3d_hit_ntf& operator=(const cli_3d_hit_ntf& from) {
    CopyFrom(from);
    return *this;
  }
  inline cli_3d_hit_ntf& operator=(cli_3d_hit_ntf&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const cli_3d_hit_ntf& default_instance() {
    return *internal_default_instance();
  }
  static inline const cli_3d_hit_ntf* internal_default_instance() {
    return reinterpret_cast<const cli_3d_hit_ntf*>(
               &_cli_3d_hit_ntf_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(cli_3d_hit_ntf& a, cli_3d_hit_ntf& b) {
    a.Swap(&b);
  }
  inline void Swap(cli_3d_hit_ntf* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(cli_3d_hit_ntf* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  cli_3d_hit_ntf* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<cli_3d_hit_ntf>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const cli_3d_hit_ntf& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const cli_3d_hit_ntf& from) {
    cli_3d_hit_ntf::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(cli_3d_hit_ntf* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cli_3d_hit_ntf";
  }
  protected:
  explicit cli_3d_hit_ntf(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kTargetAttrChangesFieldNumber = 9,
    kAttackerEntityIdFieldNumber = 1,
    kTargetEntityIdFieldNumber = 2,
    kSkillCfgIdFieldNumber = 3,
    kComboIndexFieldNumber = 4,
    kDamageFieldNumber = 5,
    kHitStateFlagFieldNumber = 6,
    kIsCriticalFieldNumber = 7,
    kTargetDeadFieldNumber = 8,
  };
  // map<int32, int64> target_attr_changes = 9;
  int target_attr_changes_size() const;
  private:
  int _internal_target_attr_changes_size() const;
  public:
  void clear_target_attr_changes();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< int32_t, int64_t >&
      _internal_target_attr_changes() const;
  ::PROTOBUF_NAMESPACE_ID::Map< int32_t, int64_t >*
      _internal_mutable_target_attr_changes();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< int32_t, int64_t >&
      target_attr_changes() const;
  ::PROTOBUF_NAMESPACE_ID::Map< int32_t, int64_t >*
      mutable_target_attr_changes();

  // uint64 attacker_entity_id = 1;
  void clear_attacker_entity_id();
  uint64_t attacker_entity_id() const;
  void set_attacker_entity_id(uint64_t value);
  private:
  uint64_t _internal_attacker_entity_id() const;
  void _internal_set_attacker_entity_id(uint64_t value);
  public:

  // uint64 target_entity_id = 2;
  void clear_target_entity_id();
  uint64_t target_entity_id() const;
  void set_target_entity_id(uint64_t value);
  private:
  uint64_t _internal_target_entity_id() const;
  void _internal_set_target_entity_id(uint64_t value);
  public:

  // uint32 skill_cfg_id = 3;
  void clear_skill_cfg_id();
  uint32_t skill_cfg_id() const;
  void set_skill_cfg_id(uint32_t value);
  private:
  uint32_t _internal_skill_cfg_id() const;
  void _internal_set_skill_cfg_id(uint32_t value);
  public:

  // uint32 combo_index = 4;
  void clear_combo_index();
  uint32_t combo_index() const;
  void set_combo_index(uint32_t value);
  private:
  uint32_t _internal_combo_index() const;
  void _internal_set_combo_index(uint32_t value);
  public:

  // int32 damage = 5;
  void clear_damage();
  int32_t damage() const;
  void set_damage(int32_t value);
  private:
  int32_t _internal_damage() const;
  void _internal_set_damage(int32_t value);
  public:

  // uint32 hit_state_flag = 6;
  void clear_hit_state_flag();
  uint32_t hit_state_flag() const;
  void set_hit_state_flag(uint32_t value);
  private:
  uint32_t _internal_hit_state_flag() const;
  void _internal_set_hit_state_flag(uint32_t value);
  public:

  // bool is_critical = 7;
  void clear_is_critical();
  bool is_critical() const;
  void set_is_critical(bool value);
  private:
  bool _internal_is_critical() const;
  void _internal_set_is_critical(bool value);
  public:

  // bool target_dead = 8;
  void clear_target_dead();
  bool target_dead() const;
  void set_target_dead(bool value);
  private:
  bool _internal_target_dead() const;
  void _internal_set_target_dead(bool value);
  public:

  // @@protoc_insertion_point(class_scope:cli_3d_hit_ntf)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        cli_3d_hit_ntf_TargetAttrChangesEntry_DoNotUse,
        int32_t, int64_t,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT64> target_attr_changes_;
    uint64_t attacker_entity_id_;
    uint64_t target_entity_id_;
    uint32_t skill_cfg_id_;
    uint32_t combo_index_;
    int32_t damage_;
    uint32_t hit_state_flag_;
    bool is_critical_;
    bool target_dead_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_client_5fbattle_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// cli_3d_skill_req

// .entity_skill_data skill = 1;
inline bool cli_3d_skill_req::_internal_has_skill() const {
  return this != internal_default_instance() && _impl_.skill_ != nullptr;
}
inline bool cli_3d_skill_req::has_skill() const {
  return _internal_has_skill();
}
inline const ::entity_skill_data& cli_3d_skill_req::_internal_skill() const {
  const ::entity_skill_data* p = _impl_.skill_;
  return p != nullptr ? *p : reinterpret_cast<const ::entity_skill_data&>(
      ::_entity_skill_data_default_instance_);
}
inline const ::entity_skill_data& cli_3d_skill_req::skill() const {
  // @@protoc_insertion_point(field_get:cli_3d_skill_req.skill)
  return _internal_skill();
}
inline void cli_3d_skill_req::unsafe_arena_set_allocated_skill(
    ::entity_skill_data* skill) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.skill_);
  }
  _impl_.skill_ = skill;
  if (skill) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:cli_3d_skill_req.skill)
}
inline ::entity_skill_data* cli_3d_skill_req::release_skill() {
  
  ::entity_skill_data* temp = _impl_.skill_;
  _impl_.skill_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::entity_skill_data* cli_3d_skill_req::unsafe_arena_release_skill() {
  // @@protoc_insertion_point(field_release:cli_3d_skill_req.skill)
  
  ::entity_skill_data* temp = _impl_.skill_;
  _impl_.skill_ = nullptr;
  return temp;
}
inline ::entity_skill_data* cli_3d_skill_req::_internal_mutable_skill() {
  
  if (_impl_.skill_ == nullptr) {
    auto* p = CreateMaybeMessage<::entity_skill_data>(GetArenaForAllocation());
    _impl_.skill_ = p;
  }
  return _impl_.skill_;
}
inline ::entity_skill_data* cli_3d_skill_req::mutable_skill() {
  ::entity_skill_data* _msg = _internal_mutable_skill();
  // @@protoc_insertion_point(field_mutable:cli_3d_skill_req.skill)
  return _msg;
}
inline void cli_3d_skill_req::set_allocated_skill(::entity_skill_data* skill) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.skill_);
  }
  if (skill) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(skill));
    if (message_arena != submessage_arena) {
      skill = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, skill, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.skill_ = skill;
  // @@protoc_insertion_point(field_set_allocated:cli_3d_skill_req.skill)
}

// -------------------------------------------------------------------

// cli_3d_skill_res

// uint64 entity_id = 1;
inline void cli_3d_skill_res::clear_entity_id() {
  _impl_.entity_id_ = uint64_t{0u};
}
inline uint64_t cli_3d_skill_res::_internal_entity_id() const {
  return _impl_.entity_id_;
}
inline uint64_t cli_3d_skill_res::entity_id() const {
  // @@protoc_insertion_point(field_get:cli_3d_skill_res.entity_id)
  return _internal_entity_id();
}
inline void cli_3d_skill_res::_internal_set_entity_id(uint64_t value) {
  
  _impl_.entity_id_ = value;
}
inline void cli_3d_skill_res::set_entity_id(uint64_t value) {
  _internal_set_entity_id(value);
  // @@protoc_insertion_point(field_set:cli_3d_skill_res.entity_id)
}

// uint32 skill_cfg_id = 2;
inline void cli_3d_skill_res::clear_skill_cfg_id() {
  _impl_.skill_cfg_id_ = 0u;
}
inline uint32_t cli_3d_skill_res::_internal_skill_cfg_id() const {
  return _impl_.skill_cfg_id_;
}
inline uint32_t cli_3d_skill_res::skill_cfg_id() const {
  // @@protoc_insertion_point(field_get:cli_3d_skill_res.skill_cfg_id)
  return _internal_skill_cfg_id();
}
inline void cli_3d_skill_res::_internal_set_skill_cfg_id(uint32_t value) {
  
  _impl_.skill_cfg_id_ = value;
}
inline void cli_3d_skill_res::set_skill_cfg_id(uint32_t value) {
  _internal_set_skill_cfg_id(value);
  // @@protoc_insertion_point(field_set:cli_3d_skill_res.skill_cfg_id)
}

// uint32 combo_index = 3;
inline void cli_3d_skill_res::clear_combo_index() {
  _impl_.combo_index_ = 0u;
}
inline uint32_t cli_3d_skill_res::_internal_combo_index() const {
  return _impl_.combo_index_;
}
inline uint32_t cli_3d_skill_res::combo_index() const {
  // @@protoc_insertion_point(field_get:cli_3d_skill_res.combo_index)
  return _internal_combo_index();
}
inline void cli_3d_skill_res::_internal_set_combo_index(uint32_t value) {
  
  _impl_.combo_index_ = value;
}
inline void cli_3d_skill_res::set_combo_index(uint32_t value) {
  _internal_set_combo_index(value);
  // @@protoc_insertion_point(field_set:cli_3d_skill_res.combo_index)
}

// .error_code err_code = 4;
inline void cli_3d_skill_res::clear_err_code() {
  _impl_.err_code_ = 0;
}
inline ::error_code cli_3d_skill_res::_internal_err_code() const {
  return static_cast< ::error_code >(_impl_.err_code_);
}
inline ::error_code cli_3d_skill_res::err_code() const {
  // @@protoc_insertion_point(field_get:cli_3d_skill_res.err_code)
  return _internal_err_code();
}
inline void cli_3d_skill_res::_internal_set_err_code(::error_code value) {
  
  _impl_.err_code_ = value;
}
inline void cli_3d_skill_res::set_err_code(::error_code value) {
  _internal_set_err_code(value);
  // @@protoc_insertion_point(field_set:cli_3d_skill_res.err_code)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// cli_3d_hit_ntf

// uint64 attacker_entity_id = 1;
inline void cli_3d_hit_ntf::clear_attacker_entity_id() {
  _impl_.attacker_entity_id_ = uint64_t{0u};
}
inline uint64_t cli_3d_hit_ntf::_internal_attacker_entity_id() const {
  return _impl_.attacker_entity_id_;
}
inline uint64_t cli_3d_hit_ntf::attacker_entity_id() const {
  // @@protoc_insertion_point(field_get:cli_3d_hit_ntf.attacker_entity_id)
  return _internal_attacker_entity_id();
}
inline void cli_3d_hit_ntf::_internal_set_attacker_entity_id(uint64_t value) {
  
  _impl_.attacker_entity_id_ = value;
}
inline void cli_3d_hit_ntf::set_attacker_entity_id(uint64_t value) {
  _internal_set_attacker_entity_id(value);
  // @@protoc_insertion_point(field_set:cli_3d_hit_ntf.attacker_entity_id)
}

// uint64 target_entity_id = 2;
inline void cli_3d_hit_ntf::clear_target_entity_id() {
  _impl_.target_entity_id_ = uint64_t{0u};
}
inline uint64_t cli_3d_hit_ntf::_internal_target_entity_id() const {
  return _impl_.target_entity_id_;
}
inline uint64_t cli_3d_hit_ntf::target_entity_id() const {
  // @@protoc_insertion_point(field_get:cli_3d_hit_ntf.target_entity_id)
  return _internal_target_entity_id();
}
inline void cli_3d_hit_ntf::_internal_set_target_entity_id(uint64_t value) {
  
  _impl_.target_entity_id_ = value;
}
inline void cli_3d_hit_ntf::set_target_entity_id(uint64_t value) {
  _internal_set_target_entity_id(value);
  // @@protoc_insertion_point(field_set:cli_3d_hit_ntf.target_entity_id)
}

// uint32 skill_cfg_id = 3;
inline void cli_3d_hit_ntf::clear_skill_cfg_id() {
  _impl_.skill_cfg_id_ = 0u;
}
inline uint32_t cli_3d_hit_ntf::_internal_skill_cfg_id() const {
  return _impl_.skill_cfg_id_;
}
inline uint32_t cli_3d_hit_ntf::skill_cfg_id() const {
  // @@protoc_insertion_point(field_get:cli_3d_hit_ntf.skill_cfg_id)
  return _internal_skill_cfg_id();
}
inline void cli_3d_hit_ntf::_internal_set_skill_cfg_id(uint32_t value) {
  
  _impl_.skill_cfg_id_ = value;
}
inline void cli_3d_hit_ntf::set_skill_cfg_id(uint32_t value) {
  _internal_set_skill_cfg_id(value);
  // @@protoc_insertion_point(field_set:cli_3d_hit_ntf.skill_cfg_id)
}

// uint32 combo_index = 4;
inline void cli_3d_hit_ntf::clear_combo_index() {
  _impl_.combo_index_ = 0u;
}
inline uint32_t cli_3d_hit_ntf::_internal_combo_index() const {
  return _impl_.combo_index_;
}
inline uint32_t cli_3d_hit_ntf::combo_index() const {
  // @@protoc_insertion_point(field_get:cli_3d_hit_ntf.combo_index)
  return _internal_combo_index();
}
inline void cli_3d_hit_ntf::_internal_set_combo_index(uint32_t value) {
  
  _impl_.combo_index_ = value;
}
inline void cli_3d_hit_ntf::set_combo_index(uint32_t value) {
  _internal_set_combo_index(value);
  // @@protoc_insertion_point(field_set:cli_3d_hit_ntf.combo_index)
}

// int32 damage = 5;
inline void cli_3d_hit_ntf::clear_damage() {
  _impl_.damage_ = 0;
}
inline int32_t cli_3d_hit_ntf::_internal_damage() const {
  return _impl_.damage_;
}
inline int32_t cli_3d_hit_ntf::damage() const {
  // @@protoc_insertion_point(field_get:cli_3d_hit_ntf.damage)
  return _internal_damage();
}
inline void cli_3d_hit_ntf::_internal_set_damage(int32_t value) {
  
  _impl_.damage_ = value;
}
inline void cli_3d_hit_ntf::set_damage(int32_t value) {
  _internal_set_damage(value);
  // @@protoc_insertion_point(field_set:cli_3d_hit_ntf.damage)
}

// uint32 hit_state_flag = 6;
inline void cli_3d_hit_ntf::clear_hit_state_flag() {
  _impl_.hit_state_flag_ = 0u;
}
inline uint32_t cli_3d_hit_ntf::_internal_hit_state_flag() const {
  return _impl_.hit_state_flag_;
}
inline uint32_t cli_3d_hit_ntf::hit_state_flag() const {
  // @@protoc_insertion_point(field_get:cli_3d_hit_ntf.hit_state_flag)
  return _internal_hit_state_flag();
}
inline void cli_3d_hit_ntf::_internal_set_hit_state_flag(uint32_t value) {
  
  _impl_.hit_state_flag_ = value;
}
inline void cli_3d_hit_ntf::set_hit_state_flag(uint32_t value) {
  _internal_set_hit_state_flag(value);
  // @@protoc_insertion_point(field_set:cli_3d_hit_ntf.hit_state_flag)
}

// bool is_critical = 7;
inline void cli_3d_hit_ntf::clear_is_critical() {
  _impl_.is_critical_ = false;
}
inline bool cli_3d_hit_ntf::_internal_is_critical() const {
  return _impl_.is_critical_;
}
inline bool cli_3d_hit_ntf::is_critical() const {
  // @@protoc_insertion_point(field_get:cli_3d_hit_ntf.is_critical)
  return _internal_is_critical();
}
inline void cli_3d_hit_ntf::_internal_set_is_critical(bool value) {
  
  _impl_.is_critical_ = value;
}
inline void cli_3d_hit_ntf::set_is_critical(bool value) {
  _internal_set_is_critical(value);
  // @@protoc_insertion_point(field_set:cli_3d_hit_ntf.is_critical)
}

// bool target_dead = 8;
inline void cli_3d_hit_ntf::clear_target_dead() {
  _impl_.target_dead_ = false;
}
inline bool cli_3d_hit_ntf::_internal_target_dead() const {
  return _impl_.target_dead_;
}
inline bool cli_3d_hit_ntf::target_dead() const {
  // @@protoc_insertion_point(field_get:cli_3d_hit_ntf.target_dead)
  return _internal_target_dead();
}
inline void cli_3d_hit_ntf::_internal_set_target_dead(bool value) {
  
  _impl_.target_dead_ = value;
}
inline void cli_3d_hit_ntf::set_target_dead(bool value) {
  _internal_set_target_dead(value);
  // @@protoc_insertion_point(field_set:cli_3d_hit_ntf.target_dead)
}

// map<int32, int64> target_attr_changes = 9;
inline int cli_3d_hit_ntf::_internal_target_attr_changes_size() const {
  return _impl_.target_attr_changes_.size();
}
inline int cli_3d_hit_ntf::target_attr_changes_size() const {
  return _internal_target_attr_changes_size();
}
inline void cli_3d_hit_ntf::clear_target_attr_changes() {
  _impl_.target_attr_changes_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< int32_t, int64_t >&
cli_3d_hit_ntf::_internal_target_attr_changes() const {
  return _impl_.target_attr_changes_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< int32_t, int64_t >&
cli_3d_hit_ntf::target_attr_changes() const {
  // @@protoc_insertion_point(field_map:cli_3d_hit_ntf.target_attr_changes)
  return _internal_target_attr_changes();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< int32_t, int64_t >*
cli_3d_hit_ntf::_internal_mutable_target_attr_changes() {
  return _impl_.target_attr_changes_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< int32_t, int64_t >*
cli_3d_hit_ntf::mutable_target_attr_changes() {
  // @@protoc_insertion_point(field_mutable_map:cli_3d_hit_ntf.target_attr_changes)
  return _internal_mutable_target_attr_changes();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_client_5fbattle_2eproto
