// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_game_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_game_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/util/json_util.h>
#include <regex>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_game_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_game_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_game_2eproto;
class cli_handshake_test_req;
struct cli_handshake_test_reqDefaultTypeInternal;
extern cli_handshake_test_reqDefaultTypeInternal _cli_handshake_test_req_default_instance_;
class cli_handshake_test_res;
struct cli_handshake_test_resDefaultTypeInternal;
extern cli_handshake_test_resDefaultTypeInternal _cli_handshake_test_res_default_instance_;
class ping_req;
struct ping_reqDefaultTypeInternal;
extern ping_reqDefaultTypeInternal _ping_req_default_instance_;
class pong_res;
struct pong_resDefaultTypeInternal;
extern pong_resDefaultTypeInternal _pong_res_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::cli_handshake_test_req* Arena::CreateMaybeMessage<::cli_handshake_test_req>(Arena*);
template<> ::cli_handshake_test_res* Arena::CreateMaybeMessage<::cli_handshake_test_res>(Arena*);
template<> ::ping_req* Arena::CreateMaybeMessage<::ping_req>(Arena*);
template<> ::pong_res* Arena::CreateMaybeMessage<::pong_res>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class cli_handshake_test_req final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cli_handshake_test_req) */ {

 public:
  const std::string msg_name() override
  {
    return "cli_handshake_test_req";    
  }
  uint32_t msg_id() override
  {
    return 2343395863;
  }
  static uint32_t get_msg_id()
  {
    return 2343395863;
  }
  
  const std::string to_json() override
  {
    std::string proto_json;
    google::protobuf::util::MessageToJsonString(*this, &proto_json);
    
    std::string name_and_id = R"({"msg_name":"cli_handshake_test_req","msg_id":2343395863)";
    if (proto_json.size() > 2)
    {
      name_and_id += ",";
    }
    proto_json.replace(0, 1, name_and_id);
    
    return proto_json;
  }
  
   void from_json(const std::string& proto_json) override
   {
     std::regex pattern(R"(^\{"msg_name":"[^"]+","msg_id":[0-9]+,)");
     std::smatch match;
     std::string msg_content = proto_json;
     if (std::regex_search(proto_json, match, pattern))
     {
         msg_content.replace(0, match[0].length(), "{");
     }

     google::protobuf::util::JsonStringToMessage(msg_content, this);
   }
  
 public:
  inline cli_handshake_test_req() : cli_handshake_test_req(nullptr) {}
  ~cli_handshake_test_req() override;
  explicit PROTOBUF_CONSTEXPR cli_handshake_test_req(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  cli_handshake_test_req(const cli_handshake_test_req& from);
  cli_handshake_test_req(cli_handshake_test_req&& from) noexcept
    : cli_handshake_test_req() {
    *this = ::std::move(from);
  }

  inline cli_handshake_test_req& operator=(const cli_handshake_test_req& from) {
    CopyFrom(from);
    return *this;
  }
  inline cli_handshake_test_req& operator=(cli_handshake_test_req&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const cli_handshake_test_req& default_instance() {
    return *internal_default_instance();
  }
  static inline const cli_handshake_test_req* internal_default_instance() {
    return reinterpret_cast<const cli_handshake_test_req*>(
               &_cli_handshake_test_req_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(cli_handshake_test_req& a, cli_handshake_test_req& b) {
    a.Swap(&b);
  }
  inline void Swap(cli_handshake_test_req* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(cli_handshake_test_req* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  cli_handshake_test_req* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<cli_handshake_test_req>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const cli_handshake_test_req& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const cli_handshake_test_req& from) {
    cli_handshake_test_req::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(cli_handshake_test_req* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cli_handshake_test_req";
  }
  protected:
  explicit cli_handshake_test_req(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClientVersionFieldNumber = 1,
  };
  // string client_version = 1;
  void clear_client_version();
  const std::string& client_version() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_client_version(ArgT0&& arg0, ArgT... args);
  std::string* mutable_client_version();
  PROTOBUF_NODISCARD std::string* release_client_version();
  void set_allocated_client_version(std::string* client_version);
  private:
  const std::string& _internal_client_version() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_client_version(const std::string& value);
  std::string* _internal_mutable_client_version();
  public:

  // @@protoc_insertion_point(class_scope:cli_handshake_test_req)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr client_version_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_2eproto;
};
// -------------------------------------------------------------------

class cli_handshake_test_res final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cli_handshake_test_res) */ {

 public:
  const std::string msg_name() override
  {
    return "cli_handshake_test_res";    
  }
  uint32_t msg_id() override
  {
    return 1705182011;
  }
  static uint32_t get_msg_id()
  {
    return 1705182011;
  }
  
  const std::string to_json() override
  {
    std::string proto_json;
    google::protobuf::util::MessageToJsonString(*this, &proto_json);
    
    std::string name_and_id = R"({"msg_name":"cli_handshake_test_res","msg_id":1705182011)";
    if (proto_json.size() > 2)
    {
      name_and_id += ",";
    }
    proto_json.replace(0, 1, name_and_id);
    
    return proto_json;
  }
  
   void from_json(const std::string& proto_json) override
   {
     std::regex pattern(R"(^\{"msg_name":"[^"]+","msg_id":[0-9]+,)");
     std::smatch match;
     std::string msg_content = proto_json;
     if (std::regex_search(proto_json, match, pattern))
     {
         msg_content.replace(0, match[0].length(), "{");
     }

     google::protobuf::util::JsonStringToMessage(msg_content, this);
   }
  
 public:
  inline cli_handshake_test_res() : cli_handshake_test_res(nullptr) {}
  ~cli_handshake_test_res() override;
  explicit PROTOBUF_CONSTEXPR cli_handshake_test_res(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  cli_handshake_test_res(const cli_handshake_test_res& from);
  cli_handshake_test_res(cli_handshake_test_res&& from) noexcept
    : cli_handshake_test_res() {
    *this = ::std::move(from);
  }

  inline cli_handshake_test_res& operator=(const cli_handshake_test_res& from) {
    CopyFrom(from);
    return *this;
  }
  inline cli_handshake_test_res& operator=(cli_handshake_test_res&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const cli_handshake_test_res& default_instance() {
    return *internal_default_instance();
  }
  static inline const cli_handshake_test_res* internal_default_instance() {
    return reinterpret_cast<const cli_handshake_test_res*>(
               &_cli_handshake_test_res_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(cli_handshake_test_res& a, cli_handshake_test_res& b) {
    a.Swap(&b);
  }
  inline void Swap(cli_handshake_test_res* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(cli_handshake_test_res* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  cli_handshake_test_res* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<cli_handshake_test_res>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const cli_handshake_test_res& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const cli_handshake_test_res& from) {
    cli_handshake_test_res::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(cli_handshake_test_res* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cli_handshake_test_res";
  }
  protected:
  explicit cli_handshake_test_res(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kServerVersionFieldNumber = 1,
  };
  // string server_version = 1;
  void clear_server_version();
  const std::string& server_version() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_server_version(ArgT0&& arg0, ArgT... args);
  std::string* mutable_server_version();
  PROTOBUF_NODISCARD std::string* release_server_version();
  void set_allocated_server_version(std::string* server_version);
  private:
  const std::string& _internal_server_version() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_server_version(const std::string& value);
  std::string* _internal_mutable_server_version();
  public:

  // @@protoc_insertion_point(class_scope:cli_handshake_test_res)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr server_version_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_2eproto;
};
// -------------------------------------------------------------------

class ping_req final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ping_req) */ {

 public:
  const std::string msg_name() override
  {
    return "ping_req";    
  }
  uint32_t msg_id() override
  {
    return 891551546;
  }
  static uint32_t get_msg_id()
  {
    return 891551546;
  }
  
  const std::string to_json() override
  {
    std::string proto_json;
    google::protobuf::util::MessageToJsonString(*this, &proto_json);
    
    std::string name_and_id = R"({"msg_name":"ping_req","msg_id":891551546)";
    if (proto_json.size() > 2)
    {
      name_and_id += ",";
    }
    proto_json.replace(0, 1, name_and_id);
    
    return proto_json;
  }
  
   void from_json(const std::string& proto_json) override
   {
     std::regex pattern(R"(^\{"msg_name":"[^"]+","msg_id":[0-9]+,)");
     std::smatch match;
     std::string msg_content = proto_json;
     if (std::regex_search(proto_json, match, pattern))
     {
         msg_content.replace(0, match[0].length(), "{");
     }

     google::protobuf::util::JsonStringToMessage(msg_content, this);
   }
  
 public:
  inline ping_req() : ping_req(nullptr) {}
  ~ping_req() override;
  explicit PROTOBUF_CONSTEXPR ping_req(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ping_req(const ping_req& from);
  ping_req(ping_req&& from) noexcept
    : ping_req() {
    *this = ::std::move(from);
  }

  inline ping_req& operator=(const ping_req& from) {
    CopyFrom(from);
    return *this;
  }
  inline ping_req& operator=(ping_req&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ping_req& default_instance() {
    return *internal_default_instance();
  }
  static inline const ping_req* internal_default_instance() {
    return reinterpret_cast<const ping_req*>(
               &_ping_req_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ping_req& a, ping_req& b) {
    a.Swap(&b);
  }
  inline void Swap(ping_req* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ping_req* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ping_req* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ping_req>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ping_req& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ping_req& from) {
    ping_req::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ping_req* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ping_req";
  }
  protected:
  explicit ping_req(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
  };
  // string id = 1;
  void clear_id();
  const std::string& id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_id();
  PROTOBUF_NODISCARD std::string* release_id();
  void set_allocated_id(std::string* id);
  private:
  const std::string& _internal_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_id(const std::string& value);
  std::string* _internal_mutable_id();
  public:

  // @@protoc_insertion_point(class_scope:ping_req)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_2eproto;
};
// -------------------------------------------------------------------

class pong_res final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pong_res) */ {

 public:
  const std::string msg_name() override
  {
    return "pong_res";    
  }
  uint32_t msg_id() override
  {
    return 3103632172;
  }
  static uint32_t get_msg_id()
  {
    return 3103632172;
  }
  
  const std::string to_json() override
  {
    std::string proto_json;
    google::protobuf::util::MessageToJsonString(*this, &proto_json);
    
    std::string name_and_id = R"({"msg_name":"pong_res","msg_id":3103632172)";
    if (proto_json.size() > 2)
    {
      name_and_id += ",";
    }
    proto_json.replace(0, 1, name_and_id);
    
    return proto_json;
  }
  
   void from_json(const std::string& proto_json) override
   {
     std::regex pattern(R"(^\{"msg_name":"[^"]+","msg_id":[0-9]+,)");
     std::smatch match;
     std::string msg_content = proto_json;
     if (std::regex_search(proto_json, match, pattern))
     {
         msg_content.replace(0, match[0].length(), "{");
     }

     google::protobuf::util::JsonStringToMessage(msg_content, this);
   }
  
 public:
  inline pong_res() : pong_res(nullptr) {}
  ~pong_res() override;
  explicit PROTOBUF_CONSTEXPR pong_res(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  pong_res(const pong_res& from);
  pong_res(pong_res&& from) noexcept
    : pong_res() {
    *this = ::std::move(from);
  }

  inline pong_res& operator=(const pong_res& from) {
    CopyFrom(from);
    return *this;
  }
  inline pong_res& operator=(pong_res&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const pong_res& default_instance() {
    return *internal_default_instance();
  }
  static inline const pong_res* internal_default_instance() {
    return reinterpret_cast<const pong_res*>(
               &_pong_res_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(pong_res& a, pong_res& b) {
    a.Swap(&b);
  }
  inline void Swap(pong_res* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(pong_res* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  pong_res* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<pong_res>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const pong_res& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const pong_res& from) {
    pong_res::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(pong_res* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pong_res";
  }
  protected:
  explicit pong_res(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
  };
  // string id = 1;
  void clear_id();
  const std::string& id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_id();
  PROTOBUF_NODISCARD std::string* release_id();
  void set_allocated_id(std::string* id);
  private:
  const std::string& _internal_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_id(const std::string& value);
  std::string* _internal_mutable_id();
  public:

  // @@protoc_insertion_point(class_scope:pong_res)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// cli_handshake_test_req

// string client_version = 1;
inline void cli_handshake_test_req::clear_client_version() {
  _impl_.client_version_.ClearToEmpty();
}
inline const std::string& cli_handshake_test_req::client_version() const {
  // @@protoc_insertion_point(field_get:cli_handshake_test_req.client_version)
  return _internal_client_version();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void cli_handshake_test_req::set_client_version(ArgT0&& arg0, ArgT... args) {
 
 _impl_.client_version_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:cli_handshake_test_req.client_version)
}
inline std::string* cli_handshake_test_req::mutable_client_version() {
  std::string* _s = _internal_mutable_client_version();
  // @@protoc_insertion_point(field_mutable:cli_handshake_test_req.client_version)
  return _s;
}
inline const std::string& cli_handshake_test_req::_internal_client_version() const {
  return _impl_.client_version_.Get();
}
inline void cli_handshake_test_req::_internal_set_client_version(const std::string& value) {
  
  _impl_.client_version_.Set(value, GetArenaForAllocation());
}
inline std::string* cli_handshake_test_req::_internal_mutable_client_version() {
  
  return _impl_.client_version_.Mutable(GetArenaForAllocation());
}
inline std::string* cli_handshake_test_req::release_client_version() {
  // @@protoc_insertion_point(field_release:cli_handshake_test_req.client_version)
  return _impl_.client_version_.Release();
}
inline void cli_handshake_test_req::set_allocated_client_version(std::string* client_version) {
  if (client_version != nullptr) {
    
  } else {
    
  }
  _impl_.client_version_.SetAllocated(client_version, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.client_version_.IsDefault()) {
    _impl_.client_version_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:cli_handshake_test_req.client_version)
}

// -------------------------------------------------------------------

// cli_handshake_test_res

// string server_version = 1;
inline void cli_handshake_test_res::clear_server_version() {
  _impl_.server_version_.ClearToEmpty();
}
inline const std::string& cli_handshake_test_res::server_version() const {
  // @@protoc_insertion_point(field_get:cli_handshake_test_res.server_version)
  return _internal_server_version();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void cli_handshake_test_res::set_server_version(ArgT0&& arg0, ArgT... args) {
 
 _impl_.server_version_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:cli_handshake_test_res.server_version)
}
inline std::string* cli_handshake_test_res::mutable_server_version() {
  std::string* _s = _internal_mutable_server_version();
  // @@protoc_insertion_point(field_mutable:cli_handshake_test_res.server_version)
  return _s;
}
inline const std::string& cli_handshake_test_res::_internal_server_version() const {
  return _impl_.server_version_.Get();
}
inline void cli_handshake_test_res::_internal_set_server_version(const std::string& value) {
  
  _impl_.server_version_.Set(value, GetArenaForAllocation());
}
inline std::string* cli_handshake_test_res::_internal_mutable_server_version() {
  
  return _impl_.server_version_.Mutable(GetArenaForAllocation());
}
inline std::string* cli_handshake_test_res::release_server_version() {
  // @@protoc_insertion_point(field_release:cli_handshake_test_res.server_version)
  return _impl_.server_version_.Release();
}
inline void cli_handshake_test_res::set_allocated_server_version(std::string* server_version) {
  if (server_version != nullptr) {
    
  } else {
    
  }
  _impl_.server_version_.SetAllocated(server_version, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.server_version_.IsDefault()) {
    _impl_.server_version_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:cli_handshake_test_res.server_version)
}

// -------------------------------------------------------------------

// ping_req

// string id = 1;
inline void ping_req::clear_id() {
  _impl_.id_.ClearToEmpty();
}
inline const std::string& ping_req::id() const {
  // @@protoc_insertion_point(field_get:ping_req.id)
  return _internal_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ping_req::set_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ping_req.id)
}
inline std::string* ping_req::mutable_id() {
  std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:ping_req.id)
  return _s;
}
inline const std::string& ping_req::_internal_id() const {
  return _impl_.id_.Get();
}
inline void ping_req::_internal_set_id(const std::string& value) {
  
  _impl_.id_.Set(value, GetArenaForAllocation());
}
inline std::string* ping_req::_internal_mutable_id() {
  
  return _impl_.id_.Mutable(GetArenaForAllocation());
}
inline std::string* ping_req::release_id() {
  // @@protoc_insertion_point(field_release:ping_req.id)
  return _impl_.id_.Release();
}
inline void ping_req::set_allocated_id(std::string* id) {
  if (id != nullptr) {
    
  } else {
    
  }
  _impl_.id_.SetAllocated(id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.id_.IsDefault()) {
    _impl_.id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ping_req.id)
}

// -------------------------------------------------------------------

// pong_res

// string id = 1;
inline void pong_res::clear_id() {
  _impl_.id_.ClearToEmpty();
}
inline const std::string& pong_res::id() const {
  // @@protoc_insertion_point(field_get:pong_res.id)
  return _internal_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void pong_res::set_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pong_res.id)
}
inline std::string* pong_res::mutable_id() {
  std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:pong_res.id)
  return _s;
}
inline const std::string& pong_res::_internal_id() const {
  return _impl_.id_.Get();
}
inline void pong_res::_internal_set_id(const std::string& value) {
  
  _impl_.id_.Set(value, GetArenaForAllocation());
}
inline std::string* pong_res::_internal_mutable_id() {
  
  return _impl_.id_.Mutable(GetArenaForAllocation());
}
inline std::string* pong_res::release_id() {
  // @@protoc_insertion_point(field_release:pong_res.id)
  return _impl_.id_.Release();
}
inline void pong_res::set_allocated_id(std::string* id) {
  if (id != nullptr) {
    
  } else {
    
  }
  _impl_.id_.SetAllocated(id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.id_.IsDefault()) {
    _impl_.id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pong_res.id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_game_2eproto
